blank_issues_enabled: false
contact_links:
  - name: Web app
    url: https://github.com/ornicar/lila/issues
    about: Issues for the web app are tracked in a separate repository. Please check for duplicates first.
  - name: Support
    url: https://discord.gg/lichess
    about: GitHub issues are meant for tracking enhancements and bugs, not general support. Instead, search the Wiki, Lichess Forum, StackOverflow, or join our Discord.
