#!/bin/sh

dir=www/i18n
mkdir -p $dir

HOST=${1:-http://lichess1.org}

for lang in en fr ru de tr sr lv bs da es ro it fi uk pt pl nl vi sv cs sk hu ca sl az nn eo tp el fp lt nb et hy af hi ar zh gl hr mk id ja bg th fa he mr mn cy gd ga sq be ka sw ps is kk io gu fo eu bn id la jv ky pi as le ta sa ml kn ko mg kb zu ur yo tl fy jb tg cv ia tc; do
  url="$HOST/assets/trans/$lang.all.json"
  echo $url;
  curl -s -o "$dir/$lang.json" $url
done

echo "References"
curl -s -o "$dir/refs.json" "$HOST/assets/trans/refs.json"

echo "Done"
