# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Android build

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/android.yml'
      - '.github/actions/build-lichobile-apk.yml'
      - 'android/**'
    branches-ignore:
      - 'l10n_master'

jobs:
  apk:
    name: Generate debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-lichobile-apk

  freeApk:
    name: Generate free debug APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build-lichobile-apk
        with:
          artifactName: "debugFreeApk"
          patchNonFree: "true"
      - name: Check non-free dependencies
        working-directory: ./android/app/build/outputs/apk/debug/
        run: |
          dexdump=$(find $ANDROID_HOME/build-tools/ -name 'dexdump' | sort -r | head -1)
          ! $dexdump app-debug.apk | grep 'Class descriptor' | grep com\/google\/firebase
          ! $dexdump app-debug.apk | grep 'Class descriptor' | grep com\/google\/android\/gms
